name: Run Tumult
on:
  push:
    branches: [ main ]
    paths:
      - doc/logo.svg
jobs:
  logos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Tidy repository
      uses: propensive/tumult@0.1.0
    - name: Autocommit changes
      uses: stefanzweifel/git-auto-commit-action@v4
