name: Update logos
on:
  push:
    branches: [ main ]
    paths:
      - doc/logo.svg
jobs:
  logos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate logos
      uses: propensive/tumult@v1
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Automated update of logos'
        file_pattern: 'doc/images/*.png'