name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Get Wrath
      uses: gautemo/fetch-api-data-action@1.0.2
      with:
        url: 'https://github.com/propensive/wrath/releases/download/0.1.0/wrath'
        file: 'wrath'
    - name: Build
      run: "./wrath -t rudiments/test -F"
