name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Get Wrath
      uses: actions/checkout@v2
      with:
        repository: 'git@github.com:propensive/wrath'
        path: 'wrath'
    - name: Build
      run: "wrath/wrath -t rudiments/test -F"
